dataset:
  name: main_cached
  
  image_root: D:\Data\Cropped Folder
  aug_mode: fully_cached        # none | fully_cached
  label_col: Abnormality(Impression)
  
  include_original: true          # include base-only image
  num_random_augs: 3              # only used for random_online / index_dependent

  # ----------------------------
  # Base pipeline (ALWAYS applied)
  # ----------------------------
  base_pipeline:
    crop_to_square: {}

    resize:
      w:
        type: simple
        args: 256
      h:
        type: simple
        args: 256

    to_tensor: {}

    normalize:
      mean:
        type: simple 
        args: [0.485, 0.456, 0.406]
      std:  
        type: simple
        args: [0.229, 0.224, 0.225]

  # ----------------------------
  # Augmentation pipeline
  # ----------------------------
  augmentations:
    rotation:
      angle:
        type: random
        args: [0, 15, 30, 60, 75, 90, 105, 120, 150, 175, 180]

    random_h_flip:
      prob:
        type: explicit
        args: [0, 1]

    random_v_flip:
      prob:
        type: explicit
        args: [0, 1]

    # color_jitter:
    #   brightness:
    #     type: random
    #     args:
    #       min: 0.8
    #       max: 1.2

    #   contrast:
    #     type: explicit
    #     args: [0.9, 1.1]

    #   hue:
    #     type: explicit
    #     args: [-0.05, 0.0, 0.05]
