data_root: D:\Data

dataset:
  name: MainDataset_Cached
  
  preprocess_inputs:
    main_dataframe: ${data_root}/Meta/test_main_features_75.xlsx
    hpv_dataframe:  ${data_root}/Meta/test_HPV_features_75.xlsx

  image_root: ${data_root}\Cropped Folder
  aug_mode: fully_cached        # none | fully_cached
  label_col: Abnormality(Impression)
  
  extra_feature_cols: ['Age']

  include_original: true          # include base-only image
  num_random_augs: 3              # only used for random_online / index_dependent

  # ----------------------------
  # Base pipeline (ALWAYS applied)
  # ----------------------------
  base_pipeline:
    # crop_to_square: {}

    - _target_: torchvision.transforms.Resize
      args:
        size:
          type: simple
          value: 224

    - _target_: torchvision.transforms.ToTensor
      args: {}

    # - _target_: torchvision.transforms.Normalize
    #   args:
    #     mean:
    #       type: simple
    #       value: [0.485, 0.456, 0.406]
    #     std:
    #       type: simple
    #       value: [0.229, 0.224, 0.225]

  
  augmentation_pipeline:

    - _target_: torchvision.transforms.RandomRotation
      args:
        degrees:
          type: random
          value: 30   # you can replace with a tuple like [-30,30] if you want both directions

    - _target_: torchvision.transforms.RandomHorizontalFlip
      args:
        p:
          type: explicit
          value: [0.0, 1.0]

    - _target_: torchvision.transforms.RandomVerticalFlip
      args:
        p:
          type: explicit
          value: [0.0, 1.0]

    


